AnimeBrainBuster/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('animes.urls'))
]

animes/urls.py
from django.urls import path
from .views import Home, criarQuiz, PesquisarQuiz, login, QuizIndividual, cadastro, MeusQuizes, excluir_quiz
from django.contrib.auth import views as auth_views

app_name = 'animes'

urlpatterns=[
    path('', Home.as_view(), name='home'),
    path('criarquiz', criarQuiz, name="criarquiz"),
    path('pesquisarquiz', PesquisarQuiz.as_view(), name="pesquisarquiz"),
    path('login', login, name='login'),
    path('quizindividual/<int:pk>',QuizIndividual.as_view(), name='quizIndividual'),
    path('cadastro', cadastro, name="cadastro"),
    path('logout', auth_views.LogoutView.as_view(template_name='login.html'),name='logout'),
    path('meusquizes', MeusQuizes.as_view(), name="meusquizes"),
    path('excluirquiz/<int:quiz_id>', excluir_quiz, name='excluirquiz'),
]

animes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Quiz(models.Model):

    nome = models.CharField(max_length=100)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="quizes_criados")

    def __str__(self):
        return f"{self.nome} - Criado por: {self.usuario.username}"


class Pergunta(models.Model):

    pergunta = models.CharField(max_length=200)
    respostaA = models.CharField(max_length=200)
    respostaB = models.CharField(max_length=200)
    respostaC = models.CharField(max_length=200)
    respostaD = models.CharField(max_length=200)
    respostaCorreta = models.CharField(max_length=200)
    quiz = models.ForeignKey("Quiz", related_name="quiz", on_delete=models.CASCADE)

    def __str__(self):
        return f'Pergunta - {self.pk} - {self.quiz.nome}'

animes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, ListView, DetailView
from .models import Quiz, Pergunta
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import JsonResponse
from django.urls import resolve

lista_de_perguntas_do_quiz = []

def limpar_lista_de_perguntas_do_quiz():
    return []

def verifica_url(request):
    current_url = request.path
    match = resolve(current_url)
    if not match.url_name == "criarquiz":
        global lista_de_perguntas_do_quiz
        lista_de_perguntas_do_quiz = limpar_lista_de_perguntas_do_quiz()

class Home(TemplateView):

    template_name = "home.html"

    def get(self, request, *args, **kwargs):
        verifica_url(request)
        return render(request, self.template_name)



def criarQuiz(request):

    global lista_de_perguntas_do_quiz
    if request.user.is_authenticated:
        if request.method == 'POST':
            button_type = request.POST.get("confirm")

            if button_type == 'criar-pergunta':
                pergunta = request.POST.get('pergunta')
                respostaA = request.POST.get('respostaA')
                respostaB = request.POST.get('respostaB')
                respostaC = request.POST.get('respostaC')
                respostaD = request.POST.get('respostaD')
                respostaCorreta = request.POST.get('resposta-correta')

                questoes = {}
                questoes['Pergunta'] = pergunta
                questoes['Resposta A'] = respostaA
                questoes['Resposta B'] = respostaB
                questoes['Resposta C'] = respostaC
                questoes['Resposta D'] = respostaD
                questoes['Resposta Correta'] = respostaCorreta

                lista_de_perguntas_do_quiz.append(questoes)
                print(lista_de_perguntas_do_quiz)
            
            if button_type == 'finalizar-quiz':
                if lista_de_perguntas_do_quiz:
                    nome_quiz = request.POST.get('nome-quiz')
                    usuario_criador = request.user
                    quiz = Quiz.objects.create(nome = nome_quiz, usuario=usuario_criador)
                    for item in lista_de_perguntas_do_quiz:
                        Pergunta.objects.create(
                            pergunta=item['Pergunta'],
                            respostaA=item['Resposta A'],
                            respostaB=item['Resposta B'],
                            respostaC=item['Resposta C'],
                            respostaD=item['Resposta D'],
                            respostaCorreta=item['Resposta Correta'],
                            quiz=quiz)
                    lista_de_perguntas_do_quiz = limpar_lista_de_perguntas_do_quiz()
                    messages.success(request, "Quiz criado com sucesso!")
                else: 
                    messages.error(request, "Para criar o quiz você deve inserir ao menos uma pergunta!")
            if button_type == "del":
                indice = request.POST.get("indice")
                try:
                    indice = int(indice)
                    indice -= 1
                except:
                    indice = None
                try:
                    if indice:
                        lista_de_perguntas_do_quiz.pop(indice)
                    else:
                        lista_de_perguntas_do_quiz.pop(0)
                    return render(request, 'criar-quiz.html', {'perguntas_do_quiz': lista_de_perguntas_do_quiz})
                except:
                    return render(request, 'criar-quiz.html', {'perguntas_do_quiz': lista_de_perguntas_do_quiz})


        return render(request, 'criar-quiz.html', {'perguntas_do_quiz': lista_de_perguntas_do_quiz})
    else:
        return redirect('animes:login')

class PesquisarQuiz(LoginRequiredMixin, ListView):
    template_name = 'pesquisar-quiz.html'
    model = Quiz

    def post(self, request, *args, **kwargs):
        verifica_url(request)
        nome_quiz = request.POST.get('nome_pesquisa_quiz')
        lista_quiz = Quiz.objects.filter(nome__icontains=nome_quiz)
    
        return render(request, self.template_name, {"object_list": lista_quiz})


class QuizIndividual(LoginRequiredMixin, ListView):
    template_name = "quiz-individual.html"
    model = Pergunta
    context_object_name = 'object_list'


    def get_queryset(self):
        ID_quiz_url = self.kwargs.get('pk')
        perguntas = Pergunta.objects.filter(quiz__pk=ID_quiz_url)
        return perguntas

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ID_quiz_url = self.kwargs.get('pk')
        nome_quiz = get_object_or_404(Quiz, pk=ID_quiz_url)
        context['quiz'] = nome_quiz.nome
        return context

    def post(self, request, *args, **kwargs):
        verifica_url(request)
        quant_perguntas = int(request.POST.get('quant_perguntas', 0)) + 1
        respostas_usuario = []
        respostas_corretas = []
        for indice in range(quant_perguntas):
            resposta = request.POST.get(f'resposta-questao-{indice}')
            if resposta is not None:
                respostas_usuario.append(resposta)
        perguntas = self.get_queryset()
        for item in perguntas:
            nome_do_quiz = item.quiz
            id_quiz = self.kwargs.get('pk')
            respostas_corretas.append(item.respostaCorreta)
        tamanho_lista = len(respostas_corretas)
        acertos, erros, total = 0, 0, 0
        for indice in range(tamanho_lista):
            if respostas_usuario[indice] == respostas_corretas[indice]:
                acertos += 1
                total += 1
            else:
                erros += 1
                total += 1
        print(acertos, erros)
        return render(request, 'resultado.html', {'erros': erros, 'acertos': acertos, 'total': total, 'quiz': nome_do_quiz, 'id_quiz': id_quiz})


def login(request):
    verifica_url(request)
    if request.method == "GET":
        return render(request, 'login.html')
    else:
        usernameOrEmail = request.POST.get('usuarioOuEmail')
        senha = request.POST.get('senha')

        userVerify = authenticate(username=usernameOrEmail, password=senha) or authenticate(email=usernameOrEmail, password=senha)

        if userVerify:
            login_django(request, userVerify)
            return redirect('animes:home')
        else:
            return render(request, 'login.html', {'erro': 'Ocorreu um erro no login'})

def cadastro(request):
    verifica_url(request)
    if request.method == "GET":
        return render(request, 'cadastro.html')
    else:
        usuario = request.POST.get('usuario')
        email = request.POST.get('email')
        senha = request.POST.get('senha')

        userVerifyUsername = User.objects.filter(username=usuario).first()
        userVerifyEmail = User.objects.filter(email=email).first()
        if userVerifyUsername or userVerifyEmail:
            return render(request, 'cadastro.html', {'erro': 'Usuário já existente'})
        else:
            newUser = User.objects.create_user(
                username=usuario,
                email=email,
                password=senha
            )
            newUser.save()
            return redirect('animes:login')



class MeusQuizes(LoginRequiredMixin, ListView):
    template_name = 'meus-quizes.html'
    model = Quiz

    def post(self, request, *args, **kwargs):
        verifica_url(request)
        nome_quiz = request.POST.get('nome_pesquisa_quiz')
        lista_quiz = Quiz.objects.filter(nome__icontains=nome_quiz, usuario=request.user)
    
        return render(request, self.template_name, {"object_list": lista_quiz})
    
    def get_queryset(self):
        return Quiz.objects.filter(usuario=self.request.user)


        


def excluir_quiz(request, quiz_id):
    verifica_url(request)
    if request.method == "DELETE":
        quiz = get_object_or_404(Quiz, id=quiz_id)
        quiz.delete()
        return JsonResponse({"success": True})
    else:
        return JsonResponse({"success": False})

animes/templates/cadastro.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Cadastro
{% endblock %}

{% block content %}
<div class="content">
    
    <form method='post' action="{% url 'animes:cadastro' %}" class="form">
        <h1 class="title-cadastro"> REALIZE SEU CADASTRO ABAIXO </h1>
        {% csrf_token %}
        
        <div class="input-group">
            <label for='IDusuario' class="label-cadastro">Usuário</label>
            <input type='text' name='usuario' id='IDusuario' class="input-cadastro" required>
        </div>
    
        <div class="input-group">
            <label for='IDemail' class="label-cadastro">Email</label>
            <input type='text' name='email' id='IDemail' class="input-cadastro" required>
        </div>
    
        <div class="input-group">
            <label for='IDsenha' class="label-cadastro">Senha</label>
            <input type='password' name='senha' id='IDsenha' class="input-cadastro" required>
        </div>
    
        <button type='submit' class="button-cadastro">CADASTRAR</button>
    </form>
    
{% if erro %}
    <p class="error-login">{{ erro }}</p>
{% endif %}
</div>
{% endblock %}

animes/templates/criar-quiz.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}

Criar Quiz
{% endblock %}

{% block content %}

{% if messages %}
    {% for message in messages %}
    <div id="error-message" class="{% if message.tags == 'error' %}alert-danger {% elif message.tags == 'success' %}alert-success{% endif %}" style="display:none">
        <span>{{ message }}</span>
    </div>
    {% endfor %}
{% endif %}
<div class="content">
    <h1 class="title-criar-quiz"> Crie seu quiz </h1>
    <div id="form-quiz-create">
        <form method='post' class="form">
            {% csrf_token %}
            
            <div class="input-group">
                <label for='IDpergunta' class="label-criar">Insira a questão</label>
                <input type='text' name='pergunta' id='IDpergunta' class="input-cadastro" required>
            </div>
            
            <div class="input-group">
                <label for='IDrespostaA' class="label-criar">Insira a resposta A</label>
                <input type='text' name='respostaA' id='IDrespostaA' class="input-cadastro" required>
            </div>
            
            <div class="input-group">
                <label for='IDrespostaB' class="label-criar">Insira a resposta B</label>
                <input type='text' name='respostaB' id='IDrespostaB' class="input-cadastro" required>
            </div>
            
            <div class="input-group">
                <label for='IDrespostaC' class="label-criar">Insira a resposta C</label>
                <input type='text' name='respostaC' id='IDrespostaC' class="input-cadastro" required>
            </div>
            
            <div class="input-group">
                <label for='IDrespostaD' class="label-criar">Insira a resposta D</label>
                <input type='text' name='respostaD' id='IDrespostaD' class="input-cadastro" required>
            </div>
            
            <div class="input-group">
                <label class="label-criar">Qual a resposta correta? </label><br>
                <input type='radio' name='resposta-correta' value='A' class="input-radio" required> A <br>
                <input type='radio' name='resposta-correta' value='B' class="input-radio" required> B <br>
                <input type='radio' name='resposta-correta' value='C' class="input-radio" required> C <br>
                <input type='radio' name='resposta-correta' value='D'class="input-radio" required> D <br>
            </div>
        
            <button type='submit' value="criar-pergunta" name='confirm' class="button-cadastro"> Criar pergunta </button>
            <button type="button" class="button-finalizar" onclick="finalizandoQuiz(event)"> Gerar Quiz</button>
        </form>
    </div>

    
    
    <div class="finalizar-quiz" id="form-quiz-finish">
        <form method='post' class="form">
            {% csrf_token %}
            <div class="input-group">
            <label for="IDnome-quiz" class="label-finalizar">Insira qual será o nome do seu quiz</label>
            <input type="text" name="nome-quiz" id='IDnome-quiz' class="input-finalizar">
            </div>
            <button type='submit' value='finalizar-quiz' name='confirm' class="button-finalizar">Finalizar Quiz </button>
        </form>
    </div>

    <div class="perguntas-criadas">
    {% if perguntas_do_quiz %}
    <h2>Perguntas Criadas </h3>
    {% for pergunta in perguntas_do_quiz %}
    <div class="pergunta">
        {% for key, value in pergunta.items %}
            {{ key }}: {{ value }}<br>
        {% endfor %}<br>
        <form method='post'>
            {% csrf_token %}
            <input type="hidden" value="{{ forloop.counter }}" name='indice'>
            <button class="excluir-item" type="submit" name="confirm" value="del">
                <span class="material-symbols-outlined">delete</span>
            </button>
        </form>
    </div>
    {% endfor %}
    {% endif %}
    </div>
</div>
{% endblock %}

animes/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Homepage
{% endblock %}

{% block content %}
<div class="content">
    <h1 class="title-home"> Anime Brain Buster </h1>

    {% if user.is_authenticated %}

    <p class="subtitle-home">
        Crie, compartilhe e participe de quizes sobre animes.<br>
        Aqui você poderá testar o seu conhecimento e testar os conhecimentos dos outros usuários sobre todos os animes.<br>
        Através das opções abaixo você pode escolher o que deseja fazer.
    </p>

    {% else %}

        <p class="subtitle-home">
            Crie, compartilhe e participe de quizes sobre animes.<br>
            Aqui você poderá testar o seu conhecimento e testar os conhecimentos dos outros usuários sobre todos os animes.<br>
            Para isso basta apenas criar seu usuário e se divertir.<br>
            Confira as opções abaixo e inicie sua jornada!!!
        </p>

    {% endif %}

    
    <div class="opcoes-home">
        {% if user.is_authenticated %}

        <a class="opcao-home" href="{% url 'animes:criarquiz' %}"> Criar Quiz</a>
        <a class="opcao-home" href="{% url 'animes:pesquisarquiz' %}"> Pesquisar Quiz</a>
        <a class="opcao-home" href="{% url 'animes:meusquizes' %}"> Meus Quizes</a>

        {% else %}

        <a class="opcao-home" href="{% url 'animes:cadastro' %}"> Crie sua Conta</a>
        <a class="opcao-home" href="{% url 'animes:login' %}"> Fazer Login</a>
        
        <a class="opcao-home" href="{% url 'animes:criarquiz' %}"> Criar Quiz</a>
        <a class="opcao-home" href="{% url 'animes:pesquisarquiz' %}"> Pesquisar Quiz</a>

        {% endif %}
        

        
        
        
    </div>
</div>
{% endblock %}

animes/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Login
{% endblock %}

{% block content %}
<div class="content">
    <h1 class="title-home"> Faça seu login </h1>
    <form method='post' action="{% url 'animes:login' %}" class="form">
        {% csrf_token %}
        <label for='IDusuarioOuEmail' class="label-search">Usuário ou Email </label>
        <input type='text' name='usuarioOuEmail' id='IDusuarioOuEmail' class="input-cadastro" required>
        <label for='IDsenha' class="label-search">Senha </label>
        <input type='password' name='senha' id='IDsenha' class="input-cadastro" required>
        <button type='submit' class='button-cadastro'>Login</button>
        <a href="{% url 'animes:cadastro' %}" class="link-cadastro">Cadastrar</a>
    </form>
<div id="error-message" display="none">
{% if erro %}
    <p class="error-login">{{ erro }}</p>
{% endif %}
</div>
</div>
{% endblock %}

animes/templates/meus-quizes.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Pesquisar Quiz
{% endblock %}

{% block content %}
<div class="content">
    <h1 class="title-home"> Pesquise pelo seus quizes criados </h1>
    <form method='post' class="form-search">
        {% csrf_token %}
        <label for='IDnome_pesquisa_quiz' class="label-search">Busque pelo nome do seu Quiz</label>
        <input name="nome_pesquisa_quiz" id='IDnome_pesquisa_quiz' class="input-cadastro">
        <button type='submit' class="button-cadastro">Pesquisar </button>
    </form>

    <div class="quiz-list-search">
        {% if object_list %}
        {% for quiz in object_list %}
        <div class="content-search-all">
            <div class="content-search">
                <a href="{% url 'animes:quizIndividual' pk=quiz.pk %}" class="link-search">
                        <span class="name-card-search">{{ quiz.nome }}</span>
                        <img src="{% static 'images/quiz.jpg' %}" class="img">
                </a>
            </div>
            <div>
                <button class="button-delete" onclick="excluirQuiz('{{quiz.id}}')">REMOVER QUIZ</button>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="content-search-no-result">
            <h1>Ops, parece que você não criou nenhum quiz com esse nome. <a class="link-no-result" href="{% url 'animes:criarquiz' %}">Crie um agora mesmo!</a></h1>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

animes/templates/pesquisar-quiz.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Pesquisar Quiz
{% endblock %}

{% block content %}
<div class="content">
    <h1 class="title-home"> Pesquise seu quiz </h1>
    <form method='post' class="form-search">
        {% csrf_token %}
        <label for='IDnome_pesquisa_quiz' class="label-search">Busque pelo nome do Quiz</label>
        <input name="nome_pesquisa_quiz" id='IDnome_pesquisa_quiz' class="input-cadastro">
        <button type='submit' class="button-cadastro">Pesquisar </button>
    </form>

    <div class="quiz-list-search">
        {% if object_list %}
        {% for quiz in object_list %}
        <a href="{% url 'animes:quizIndividual' pk=quiz.pk %}" class="link-search">
            <div class="content-search">
                <span class="name-card-search">{{ quiz.nome }}</span>
                <img src="{% static 'images/quiz.jpg' %}">
            </div>
        </a>
        {% endfor %}
        {% else %}
        <div class="content-search-no-result">
            <h1>Ops, não encontramos nenhum quiz com esse nome, pesquise por outra coisa ou <a class="link-no-result" href="{% url 'animes:criarquiz' %}">crie agora mesmo um quiz!</a></h1>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

animes/templates/quiz-individual.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Quiz {{ quiz }}
{% endblock %}

{% block content %}
<div class="content">
    <div class="content-quiz">
        <h1 class="title-home">{{ quiz }}</h1>
        <form method='post' class="form-quiz">
        {% csrf_token %}
        {% for pergunta in object_list %}
        <div class="question-quiz none" style="{% if forloop.counter == 1 %}display:flex; {% endif %}" id="question-quiz-{{ forloop.counter }}">
            <label class="question-quiz-ask">{{ pergunta.pergunta }}</label>
            <label class="label-input-quiz"><input type='radio' name='resposta-questao-{{ forloop.counter }}' value="A" class='question-quiz-answer' required> {{ pergunta.respostaA }}</label>
            <label class="label-input-quiz"><input type='radio' name='resposta-questao-{{ forloop.counter }}' value="B" class='question-quiz-answer' required> {{ pergunta.respostaB }}</label>
            <label class="label-input-quiz"><input type='radio' name='resposta-questao-{{ forloop.counter }}' value="C" class='question-quiz-answer' required> {{ pergunta.respostaC }}</label>
            <label class="label-input-quiz"><input type='radio' name='resposta-questao-{{ forloop.counter }}' value="D" class='question-quiz-answer' required> {{ pergunta.respostaD }}</label>
            <button class="next-button" onclick="showBackQuestionQuiz({{ forloop.counter }})" type="button">BACK</button>
            <button class="next-button" onclick="showNextQuestionQuiz({{ forloop.counter|add:1 }})" type="button">NEXT</button>
            
            {% if forloop.last %}
                <input type="hidden" name="quant_perguntas" value="{{forloop.counter}}">
                <button type='submit' class="button-finish">Verificar Resultado</button>
            {% endif %}
        </div>
        
        {% endfor %}
        
        </form>
    </div>
</div>
{% endblock %}

animes/templates/resultado.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Resultado do quiz {{ quiz }}
{% endblock %}

{% block content %}
<div class="content-result">
    <div class="result">
        <h1 class="message-result">Você finalizou o quiz <span class="title-quiz">{{ quiz }} </span>com um total de {{acertos}} acertos de {{total }} perguntas!</h1>
        <a href="{% url 'animes:quizIndividual' pk=id_quiz  %}" class="link-result">Clique aqui para refazer o teste</a>
        <a href="{% url 'animes:pesquisarquiz' %}" class="link-result">Clique aqui para fazer outros testes</a>


    </div>
</div>
{% endblock %}