AnimeBrainBuster/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('animes.urls'))
]

animes/urls.py
from django.urls import path
from .views import Home, criarQuiz, PesquisarQuiz, login, QuizIndividual, cadastro, MeusQuizes, excluir_quiz
from django.contrib.auth import views as auth_views

app_name = 'animes'

urlpatterns=[
    path('', Home.as_view(), name='home'),
    path('criarquiz', criarQuiz, name="criarquiz"),
    path('pesquisarquiz', PesquisarQuiz.as_view(), name="pesquisarquiz"),
    path('login', login, name='login'),
    path('quizindividual/<int:pk>',QuizIndividual.as_view(), name='quizIndividual'),
    path('cadastro', cadastro, name="cadastro"),
    path('logout', auth_views.LogoutView.as_view(template_name='login.html'),name='logout'),
    path('meusquizes', MeusQuizes.as_view(), name="meusquizes"),
    path('excluirquiz/<int:quiz_id>', excluir_quiz, name='excluirquiz'),
]

templates/base.html
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block titulo %}
        {% endblock %}
    </title>
   
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    {% include 'footer.html' %}
</body>
<script src="{% static 'js/script.js' %}"></script>
</html>

templates/footer.html
<div class='navbar footer'>
    <h1>AnimeBrainBuster</h1>
<div>

templates/navbar.html
<div class="navbar">
    
    <a href="{% url 'animes:home' %}" class="opcoes">Home</a>
    <a href="{% url 'animes:criarquiz' %}" class="opcoes">Criar Quiz</a>
    <a href="{% url 'animes:pesquisarquiz' %}" class="opcoes">Pesquisar Quiz</a>
    <a href="{% url 'animes:meusquizes' %}" class="opcoes">Meus Quizes</a>
    {% if user.is_authenticated %}
    <a href="{% url 'animes:logout' %}" class="opcoes">Sair</a>
    {% else %}
    <a href="{% url 'animes:login' %}" class="opcoes">Login</a>
    
    {% endif %}
</div>